### ISSUE TITLE
Check internal links to _talk and _user pages

### ISSUE THREAD

**Issue by smgriffin2** [micro-manager/micro-manager.org#35]
`_talk` and `_users` were moved under _pages, renamed `talk` and `users`

Need to check if any links were broken in this process.

**Comment by marktsuchida** [comment]
(Sam's commit making this move is https://github.com/micro-manager/micro-manager.org/commit/89c0bafe1919e78b30adea3cf0c8373d9c02ad32.)

Working on this now.

I don't think the links to `_talk` (page Discussion) pages got imported in the first place. They should be linked to the corresponding pages.

Links to users appear to still be in the form `[Mark Tsuchida](User:Mark_Tsuchida "wikilink")`, so they can be batch-converted.

There are also links like `[talk](User_talk::Mark_Tsuchida "wikilink")`, but none of them have real content and the links should be deleted.
